#!/usr/bin/env python3
"""Monty the Motivator

A simple command-line motivator :-)
"""

import random
from pathlib import Path


def main():
    """Main entry point"""
    hints = [
        "I know you can manage it :-)",
        "What about to take 5 minute break?",
        "What about to grab a mug of good coffee or tea?",
        "What about of doing 2 push-ups?",
    ]
    name_file = Path("name")
    history_file = Path("history")

    if not name_file.exists():
        print("Hi, I'm Monty, your command-line motivator.")
        name = input("What's your name?:\n")
        name_file.write_text(name, encoding="utf-8")
        print(f"Nice to meet you {name}.", end="")
    else:
        name = name_file.read_text(encoding="utf-8")
        print(f"Hi {name}.", end="")

    # TODO: improve the style by changing 'your' to 'the', also remove ':'
    problem = input(" What's your problem?:\n")
    answer = f"It's just another challenge. {random.choice(hints)}"
    print(answer)
    with history_file.open("a", encoding="utf-8") as histf:
        # Separate entries by additional newline (hence \n*2)
        histf.write(problem + "\n" + answer + "\n"*2)


if __name__ == "__main__":
    main()
