#!/usr/bin/env python3
"""Monty the Motivator

A simple command-line motivator :-)
"""


import random


def main():
    """Main entry point"""
    hints = [
        "I know you can manage it :-)",
        "What about to take 5 minute break?",
        "What about to grab a mug of good coffee or tea?",
    ]
    input("Hi <user>. What's your problem?:\n")
    print(f"It's just another challenge. {random.choice(hints)}")


if __name__ == "__main__":
    main()
